user nginx;
worker_processes auto;
events { worker_connections 2048; }

http {
    # Trava DDoS
    limit_req_zone $binary_remote_addr zone=trava_ddos:10m rate=10r/s;
    limit_req_status 429;

    server {
        listen 80;
        
        location / {
            limit_req zone=trava_ddos burst=15 nodelay;
            root /usr/share/nginx/html;
            index index.html;
        }

        location /api/ {
            limit_req zone=trava_ddos burst=10 nodelay;
            proxy_pass http://java_api:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}